language: java
jdk:
  - oraclejdk8
sudo: required
dist: trusty
install:
-  |
    cat <<EOF

    Running build with the following parameters

    FEATURE_BRANCH=${FEATURE_BRANCH}
    SPRING_CLOUD_BUILD=${SPRING_CLOUD_BUILD}
    MVN_GOAL=${MVN_GOAL}
    VERSION=${VERSION}
    MILESTONE=${MILESTONE}
    MVN_PROFILE=${MVN_PROFILE}
    TRAVIS_BRANCH=${TRAVIS_BRANCH}
    TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
    TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}

    EOF
script:
#- ./mvnw -s .settings.xml $MVN_GOAL $MVN_PROFILE -nsu --batch-mode > log.log || echo "FAILED!" &&  grep -v '^.*Download.* http.*$' log.log && exit 1
- './mvnw -s .settings.xml $MVN_GOAL $MVN_PROFILE -nsu --batch-mode -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - FEATURE_BRANCH=$(echo ${TRAVIS_BRANCH} | grep -v "master" && echo true || echo false)
  - SPRING_CLOUD_BUILD=$(echo ${TRAVIS_REPO_SLUG} | grep -q "^spring-cloud/.*$" && echo true || echo false)
  - MVN_GOAL=$([ "${TRAVIS_PULL_REQUEST}" == "false" -a "${TRAVIS_TAG}" == "" -a "${FEATURE_BRANCH}" == "false" -a "${SPRING_CLOUD_BUILD}" == "true" ] && echo deploy || echo install)
  - VERSION=$(mvn validate | grep Building | head -1 | sed -e 's/.* //')
  - MILESTONE=$(echo ${VERSION} | egrep 'M|RC' && echo true || echo false)
  - MVN_PROFILE=$([ "${MILESTONE}" == "true" ] && echo -P milestone)
  - TERM=dumb

